name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step Actions 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Solve Dependencies
        run: | 
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install pylint
          pip install poetry
          pip install -U pytest

      - name: App Test
        run: coverage run -m pytest

      - name: Build Doc
        run: |
          sphinx-apidoc -o doc .
          cd src/doc
          make html

      - name: Build Container
        run: |
          docker-compose build -t trabalho-final
          docker-compose up -d

      - name: Publish App
        run: |
          cd /poetry-tf
          poetry config pypi-token.api pypi-AgEIcHlwaS5vcmcCJDMyMmNmNDI2LThhYjQtNGVhNS1hODZiLThmMTY0MDc5YmVmZQACKlszLCI3MzYxOGRhMy0wNzFkLTRjZDktOTZlZC1jNTBmZjFmY2MyYTciXQAABiCq4M2_T2KdcgZOEaKVU_iLSU0ehfLKY3aiMeuld1ruJQ
          poetry install --no-dev
          poetry build
          poetry publish