name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step Actions 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Solve Dependencies
        run: | 
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx
          pip install sphinx-rtd-theme
          pip install flake8
          pip install poetry
          pip install -U pytest

      - name: Set Virtual Environment
        run: |
          sudo apt-get install python3-venv
          python3 -m venv env

      - name: Lint Step
        run: |
          cd src
          flake8 --ignore=E302,E101,E131,W191,W293,W292,W291 --count --select=E9,F63,F7,F82 --exclude=*.pyc,migrations --show-source --statistics

      - name: App Test
        run: |
          cd  tests
          python __init__.py

      - name: Build Doc
        run: |
          sphinx-apidoc -o doc .
          cd src/doc
          make html

      - name: Build Container
        run: |
          docker-compose build -t trabalho-final
          docker-compose up -d

      - name: Publish App
        run: |
          cd /poetry-tf
          poetry config pypi-token.api pypi-AgEIcHlwaS5vcmcCJDMyMmNmNDI2LThhYjQtNGVhNS1hODZiLThmMTY0MDc5YmVmZQACKlszLCI3MzYxOGRhMy0wNzFkLTRjZDktOTZlZC1jNTBmZjFmY2MyYTciXQAABiCq4M2_T2KdcgZOEaKVU_iLSU0ehfLKY3aiMeuld1ruJQ
          poetry install --no-dev
          poetry build
          poetry publish